In [ ]:
df = "msg"
type (df)

str

In [ ]:
# IF STATEMENT
# if condition:
# true block

In [ ]:
a = 5
print ("Program Starts")
if a == 5:
   print ("The value of A is 5")
print ("Program Ends")

Program Starts
The value of A is 5
Program Ends


In [ ]:
a = 5
print ("Program Starts")
if a == 50:
   print ("The value of A is 5")
else:
   print ("The value is something else")
print ("Program Ends")

Program Starts
The value is something else
Program Ends


In [ ]:
a = 5
print ("Program Starts")
if a == 5:
   print ("The value of A is 5")
elif a == 1:
   print("One")
else:
   print ("The value is something else...")
print ("Program Ends")

Program Starts
The value of A is 5
Program Ends


In [ ]:
a = 5
if a == 50:
  print("Print Five")
else:
 print("Not Five")

Not Five


In [ ]:
# Based on the user input, print the corresponding day of the week if 1-> Sunday, 2-> Monday, ....

a = 70
if a == 1:
 print ("Sunday")
elif a == 2:
  print ("Monday")
elif a == 3:
  print ("Tuesday")
elif a == 4:
  print ("Wednesday")
elif a == 5:
  print ("Thursday")
elif a == 6:
  print ("Friday")
elif a == 7:
  print ("Saturday")
else:
 print ("Not A Day of The Week")

Not A Day of The Week


In [ ]:
msg = "I am Siddhartha"
len(msg)
print (len(msg))

15


In [ ]:
msg.upper()

'I AM SIDDHARTHA'

In [ ]:
msg.lower()

'i am siddhartha'

In [ ]:
print(msg.upper())
print(msg.lower())
print(msg.upper())
print(msg.swapcase())

I AM SIDDHARTHA
i am siddhartha
I AM SIDDHARTHA
i AM sIDDHARTHA


In [ ]:
msg = "       Sid        "
print(type(msg))
print(len(msg))
print(len(msg.strip()))

<class 'str'>
18
3


In [ ]:
msg = "       Sid shgdvfdsh       "
print(type(msg))
print(len(msg))
print(len(msg.strip()))

<class 'str'>
27
13


In [ ]:
msg = "       Sid \shg\dvfdsh       "
print(msg)
print(type(msg))
print(len(msg.strip()))

       Sid \shg\dvfdsh       
<class 'str'>
15


In [ ]:
msg = "2, 3, 4"
print(msg.split(","))

['2', ' 3', ' 4']


In [ ]:
msg = "S, I, D"
print(msg.split(","))

['S', ' I', ' D']


In [ ]:
msg = "S; I; D"
print(msg.split(";"))

['S', ' I', ' D']


In [ ]:
msg = "S , I, D"
print(msg.split(";"))

['S , I, D']


In [ ]:
msg = "S,I,D"
df = msg.split(",")
for item in df:
 print(item)

S
I
D


In [ ]:
msg = "1, 2, 3"
df = msg.split(",")
for item in df:
 print(item)

1
 2
 3


In [ ]:
msg = "S, I, D"
df = msg.split(",")
for item in df:
 print(item, type(item))

S <class 'str'>
 I <class 'str'>
 D <class 'str'>


In [ ]:
msg = "1, 2, 3"
df = msg.split(",")
print(df)
for item in df:
  temp = int(item)
  print(item,type(item),temp,type(temp))

['1', ' 2', ' 3']
1 <class 'str'> 1 <class 'int'>
 2 <class 'str'> 2 <class 'int'>
 3 <class 'str'> 3 <class 'int'>


In [ ]:
msg = "1, 2, 3"
df = msg.split(",")
print(df)
sum = 0
for item in df:
  temp = int(item)
  sum = sum + temp
  print(item,type(item),temp,type(temp))
print(sum)

['1', ' 2', ' 3']
1 <class 'str'> 1 <class 'int'>
 2 <class 'str'> 2 <class 'int'>
 3 <class 'str'> 3 <class 'int'>
6


In [ ]:
msg = "1, 2, 3"
df = msg.split(",")
print(df)
sum = 10
for item in df:
  temp = int(item)
  sum = sum + temp
  print(item,type(item),temp,type(temp))
print(sum)

['1', ' 2', ' 3']
1 <class 'str'> 1 <class 'int'>
 2 <class 'str'> 2 <class 'int'>
 3 <class 'str'> 3 <class 'int'>
16


In [ ]:
name = input("Enter user name: ")
password = input("Enter the password: ")

print("Your username: {} and password entered is: {}". format(name, password))

Enter user name: Siddhartha
Enter the password: Oli@1011
Your username: Siddhartha and password entered is: Oli@1011


In [ ]:
for i in range(1,25,7):
  print(i)

1
8
15
22


In [ ]:
# Find sum of n multiples of 2 where n is user input
sum = 0
for i in range(2,20,2):
 print(i)
 sum = sum + i

print(sum)

2
4
6
8
10
12
14
16
18
90


In [ ]:
nlist = ["abc", "oli", "sid", 23, 6.9, "debo_sid"]
print(nlist)

['abc', 'oli', 'sid', 23, 6.9, 'debo_sid']


In [ ]:
nlist = ["abc", "oli", "sid", 23, 6.9, "debo_sid"]
print(nlist["abc"])

TypeError: ignored

In [ ]:
listex = ["one", "two", "three", 'four']
print(listex)
print(listex[3])

['one', 'two', 'three', 'four']
four


In [ ]:
if "three" in listex:
  print("Success")

Success


In [ ]:
listex.append("five")
listex

['one', 'two', 'three', 'four', 'five']

In [ ]:
listex.pop()
listex

['one', 'two', 'three', 'four']

In [ ]:
listex.remove("one")
listex

['two', 'three', 'four']

In [ ]:
len(listex)

3

In [ ]:
listex.reverse()
listex

['four', 'three', 'two']

In [ ]:
listex.sort()
listex

['four', 'three', 'two']

In [ ]:
def fname():
  print("I am your first function...")
fname()

I am your first function...


In [ ]:
def fname():
  print("I am your first function...")
  df = "Success"
  return df
status = fname()
print(status)

I am your first function...
Success


In [ ]:
def fname():
  print("I am your first function...")
  df = "Success"
  return df, True
status, flag = fname()
print(status, flag)

I am your first function...
Success True


In [ ]:
def fname(n):
  print("I am your first function...",n)
  df = "Success"
  return df, True
name = "Siddy_boi"
status, flag = fname(name)
print(status, flag)

I am your first function... Siddy_boi
Success True


In [ ]:
lst = [1, 2, 3]
for item in lst:
   print(item)

1
2
3


In [ ]:
for item in range(0, len(lst), 1):
 print(lst[item])

1
2
3


In [ ]:
file = open("Sample.txt","w+")
file.write("This is my first line to file from python")

41

In [ ]:
file.write("This is my first line to file from python")

41

In [ ]:
file = open("Sample.txt","w+")
file.write("This is my first line to file from python\n")

42

In [ ]:
file.write("This is my first line to file from python\n")

42

In [ ]:
file.close()

In [ ]:
file = open("Sample.txt","r+")
file.readline()

'This is my first line to file from python\n'

In [ ]:
file.readlines()

['This is my first line to file from python\n',
 'This is my first line to file from python\n']

In [ ]:
a = 0
while a < 7:
  res = a * a
  print (a, res)
  a = a + 1

0 0
1 1
2 4
3 9
4 16
5 25
6 36


In [ ]:
a = 0
while a < 7:
  res = a * a
  print (a, res)
  a = a + 2

0 0
2 4
4 16
6 36


In [ ]:
a = 0
while a < 7:
  res = a * a
  print (a, res)
  a = a + 8

0 0


In [ ]:
a = 2
while a < 7:
  res = a * a
  print (a, res)
  a = a + 1

2 4
3 9
4 16
5 25
6 36


In [ ]:
a = 2
while a < 7:
  res = a * a
  print (a, res)
  a = a + 8

2 4


In [ ]:
for i in range (1,10,1):
  if i == 7:
    break
  print(i)

1
2
3
4
5
6


In [ ]:
for i in range (1,10,1):
  if i == 9:
    break
  print(i)

1
2
3
4
5
6
7
8


In [ ]:
for i in range (1,10,1):
  if i == 10:
    break
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range (1,10,1):
  if i == 11:
    break
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range (1,10,1):
  if i == 12:
    break
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range (1,10,1):
  if i == 7:
    continue
  print(i)

1
2
3
4
5
6
8
9


In [ ]:
for i in range (1,10,1):
  if i == 2:
    continue
  print(i)

1
3
4
5
6
7
8
9


In [ ]:
for i in range (1,10,1):
  if i == 1:
    continue
  print(i)

2
3
4
5
6
7
8
9


In [ ]:
list_ex = ["MEW", "HALUM", "MEW", "HALUM", "SIDDY", "OLI"]
set_ex = set(list_ex)
print(list_ex)
print(set_ex)

['MEW', 'HALUM', 'MEW', 'HALUM', 'SIDDY', 'OLI']
{'HALUM', 'OLI', 'MEW', 'SIDDY'}


In [ ]:
list_ex = ["MEW", "HALUM", "MEW", "HALUM", "SIDDY", "OLI"]
set_ex = set(list_ex)
back = list(set_ex)
print(list_ex)
print(set_ex)
print(back)
print(type(list_ex))
print(type(set_ex))
print(type(back))

['MEW', 'HALUM', 'MEW', 'HALUM', 'SIDDY', 'OLI']
{'HALUM', 'OLI', 'MEW', 'SIDDY'}
['HALUM', 'OLI', 'MEW', 'SIDDY']
<class 'list'>
<class 'set'>
<class 'list'>


In [ ]:
# Create a list of 10 names that are random and repeating. Identify the unique items annd their count.

names = []
for i in range(0,10,1):
  name = input("Enter The Name:")
  name = name.strip()
  name = name.upper()
  names.append(name)
print(names)

Enter The Name:SID
Enter The Name:OLI
Enter The Name:SID
Enter The Name:SID
Enter The Name:OLI
Enter The Name:THOMAS
Enter The Name:THOMAS
Enter The Name:MEW
Enter The Name:HALUM
Enter The Name:MEW
['SID', 'OLI', 'SID', 'SID', 'OLI', 'THOMAS', 'THOMAS', 'MEW', 'HALUM', 'MEW']


In [ ]:
unique_names = set(names)
print(unique_names)

{'THOMAS', 'MEW', 'SID', 'HALUM', 'OLI'}


In [ ]:
unique_names = set(names)
for search in unique_names:
  search = "MEW"
  for item in names:
    if search == item:
      print("Found")

Found
Found
Found
Found
Found
Found
Found
Found
Found
Found


In [ ]:
for search in unique_names:
  count = 0
  for item in names:
    if search == item:
      count = count + 1
  print(search,count)

THOMAS 2
MEW 2
SID 3
HALUM 1
OLI 2


In [ ]:
my_dict = {
    "Name": "SIDDHARTHA SINHA",
    "Phone No": 8582873442,
    "Email ID": "siddhartha.sinha@msds.christuniversity.in",
}
print(my_dict["Name"])

SIDDHARTHA SINHA


In [ ]:
my_dict = {
    "Name": "SIDDHARTHA SINHA",
    "Phone No": 8582873442,
    "Email ID": "siddhartha.sinha@msds.christuniversity.in",
}
print(my_dict["Phone No"])

8582873442


In [ ]:
my_dict["Address"] = "CHRIST RESIDENCE"
print(my_dict)

{'Name': 'SIDDHARTHA SINHA', 'Phone No': 8582873442, 'Email ID': 'siddhartha.sinha@msds.christuniversity.in', 'Address': 'CHRIST RESIDENCE'}


In [ ]:
print(my_dict["akdum-bakdum"])

KeyError: ignored

In [ ]:
my_dict.keys()

dict_keys(['Name', 'Phone No', 'Email ID', 'Address'])

In [ ]:
print(my_dict.keys())
for key in my_dict.keys():
  print(key)

dict_keys(['Name', 'Phone No', 'Email ID', 'Address'])
Name
Phone No
Email ID
Address


In [ ]:
my_dict.values()

dict_values(['SIDDHARTHA SINHA', 8582873442, 'siddhartha.sinha@msds.christuniversity.in', 'CHRIST RESIDENCE'])

In [ ]:
students = {
    "Names": ["Mew", "Halum", "Oli"],
    "Roll No": [1, 2, 3],
}
for Names in students["Names"]:
  print(Names)

Mew
Halum
Oli


In [ ]:
students = {
    "Names": ["Mew", "Halum", "Oli"],
    "Roll No": [1, 2, 3],
}
print(students["Names"][0])

Mew


In [ ]:
students = {
    "Names": ["Mew", "Halum", "Oli"],
    "Roll No": [1, 2, 3],
}
print(students["Names"][1])

Halum


In [ ]:
students = {
    "Names": ["Mew", "Halum", "Oli"],
    "Roll No": [1, 2, 3],
}
print(students["Names"][2])

Oli


In [ ]:
students = {
    "Names": ["Mew", "Halum", "Oli"],
    "Roll No": [1, 2, 3],
}
print(students["Names"][3])

IndexError: ignored

In [ ]:
MScDSB = [
    {
        "Name": "Debolina Chatterjee",
        "Roll": 1,
        "Email ID": "debolina.chatterjee@msds.christuniversity.in",
        "Phone": 8945513808
    },
    {
        "Name": "Siddhartha Sinha",
        "Roll": 2,
        "Email ID": "siddhartha.sinha@msds.christuniversity.in",
        "Phone": 8582873442
    },
    {
        "Name": "Halum Mew            ",
        "Roll": 3,
        "Email ID": "halum.mew@msds.christuniversity.in            ",
        "Phone": 7894561230
    }
]
for student in MScDSB:
  for key in student.keys():
    print(student[key], end = "\t")
  print()

Debolina Chatterjee	1	debolina.chatterjee@msds.christuniversity.in	8945513808	
Siddhartha Sinha	2	siddhartha.sinha@msds.christuniversity.in	8582873442	
Halum Mew            	3	halum.mew@msds.christuniversity.in            	7894561230	


In [ ]:
MScDSB = [
    {
        "Name": "Debolina Chatterjee",
        "Roll": 1,
        "Email ID": "debolina.chatterjee@msds.christuniversity.in",
        "Phone": 8945513808
    },
    {
        "Name": "Siddhartha Sinha",
        "Roll": 2,
        "Email ID": "siddhartha.sinha@msds.christuniversity.in",
        "Phone": 8582873442
    },
    {
        "Name": "Halum Mew            ",
        "Roll": 3,
        "Email ID": "halum.mew@msds.christuniversity.in            ",
        "Phone": 7894561230
    }
]
for student in MScDSB:
  print(student)
  for key in student.keys():
    print(student[key], end = "\t")
  print()

{'Name': 'Debolina Chatterjee', 'Roll': 1, 'Email ID': 'debolina.chatterjee@msds.christuniversity.in', 'Phone': 8945513808}
Debolina Chatterjee	1	debolina.chatterjee@msds.christuniversity.in	8945513808	
{'Name': 'Siddhartha Sinha', 'Roll': 2, 'Email ID': 'siddhartha.sinha@msds.christuniversity.in', 'Phone': 8582873442}
Siddhartha Sinha	2	siddhartha.sinha@msds.christuniversity.in	8582873442	
{'Name': 'Halum Mew            ', 'Roll': 3, 'Email ID': 'halum.mew@msds.christuniversity.in            ', 'Phone': 7894561230}
Halum Mew            	3	halum.mew@msds.christuniversity.in            	7894561230	


In [ ]:
import numpy

In [ ]:
numpy.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
import numpy as np

In [ ]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
np.ones(100,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones(100,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones("Hundred",dtype=str)

TypeError: ignored

1) LOAD A CSV AND SET A NEW COLOUMN NAMES.
2) RENAME COLOUMN NAME ( ONE COLOUMN, MULTIPLE COLOUMN)
3) LOAD A DATASET AND SET ONE COLOUMN AS INDEX COLOUMN
4) SPLIT YOUR DATA INTO MULTIPLE FILES WITH REPEAT TO ROWS AND COLOUMNS. LOAD THE DIFFERENT FILES . AND MERGE THEM TO THE FINAL FILE(MERGE AND JOIN)

In [ ]:
import pandas as pd

Write a python program with the following specification.
There will be a function name with create_dataset which will take a dictionary, filename, no. of rows as arguments.
The dictionary is having the following structure:
{
  "column" [domain & value]
  "
  "
}
Your function will select random values for each of the domains and create a row for you. The number of rows that has to be created is the parameter that has been taken. Save the file with the required number of rows. Load this dataset using pandas and display basic details.
